version: '3.8'

services:
  codexy-api-staging:
    container_name: codexy-api-staging
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.staging        
    ports:
      - "5300:8080"          # ✅ puerto diferente para staging
    networks:
      - codexy-network
    labels:
      - com.codexy.environment=staging

networks:
  codexy-network:
    external: true
