version: '3.8'

services:
  codexy-api-prod:
    container_name: codexy-api-prod
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - codexy-mssql-prod
    ports:
      - "5400:8080"
    networks:
      - codexy-network
    labels:
      - com.codexy.environment=prod

networks:
  codexy-network:
    external: true
