version: '3.8'

services:
  codexy-api-develop:
    container_name: codexy-api-develop
    build:
      context: ../..          # raíz del proyecto
      dockerfile: Dockerfile  # Dockerfile del backend
    restart: always
    env_file:
      - .env.dev
    depends_on:
      - codexy-mssql-develop
    ports:
      - "5100:8080"
    networks:
      - codexy-network
    labels:
      - com.codexy.environment=develop

networks:
  codexy-network:
    external: true  # red ya creada por el stack de bases de datos
